"""empty message

Revision ID: 0cd0f0e5909f
Revises: 12ed8aeba2a5
Create Date: 2024-08-25 09:26:24.588673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0cd0f0e5909f'
down_revision: Union[str, None] = '12ed8aeba2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'thumbnail',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'review_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('documents', 'editable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('documents', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('documents', 'editable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('documents', 'review_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('documents', 'thumbnail',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
