"""empty message

Revision ID: 1d3099589136
Revises: 0cd0f0e5909f
Create Date: 2024-08-25 09:57:37.597010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1d3099589136"
down_revision: Union[str, None] = "0cd0f0e5909f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "summary", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.create_unique_constraint(None, "tags", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="unique")
    op.alter_column(
        "documents", "summary", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
