"""empty message

Revision ID: cdc0395b9db7
Revises: e3d89c5b3b04
Create Date: 2024-08-25 16:31:26.198744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "cdc0395b9db7"
down_revision: Union[str, None] = "e3d89c5b3b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(None, "documents", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "user_id")
    # ### end Alembic commands ###
